### ISSUE TITLE
Open Obligations Date Range would cause issues on year boundaries

### ISSUE THREAD

**Issue by MJCallahanPage** [hmrc/view-vat-returns-frontend#222]
The following code would lead to some unexpected behaviour at the turn of the year.

It uses the current year and then grabs any open obligations from 1-1-YYYY to the 31-12-YYYY. If a user had two open obligations when they looked at their account in December and then came back in January to view them again then they would disappear as the year has now moved on so it would be selecting from 1-1-YYYY+1 to 31-1-YYYY+1.

For open obligations, you do not need to provide a From and To date. Therefore it may be better to remove this all together; this would cater for displaying overdue obligations which are > 1 year old too.

https://github.com/hmrc/view-vat-returns-frontend/blob/fd98cb005a4b9d79607c88b3ad0e96ddfb15c523/app/services/ReturnsService.scala#L43-L53

**Comment by TomDudley92** [comment]
There is a Jira task on the backlog regarding this that was raised a long time ago (BTAT-2742). Unfortunately because of other work taking priority (as this will not be a problem until 2019), we have not been able to address this since it was raised.

The existing Jira story could be used to track the work in the future (the description/title of it may need to be updated to cover all occurrences of the issue).

**Comment by MJCallahanPage** [comment]
@TomDudley92 - that's great, thanks for letting us know. Just wanted to flag it on GitHub so that it was a reminder.

The existing story can be used 👍

**Comment by miranda-hawkes** [comment]
Done in previous story

**Comment by miranda-hawkes** [comment]
Done in previous story
